@startuml webgl_pipeline

scale 3

component "Vertex Shader" as vs{
rectangle Attributes
}

rectangle Memory{
    rectangle "Vertex Buffer Objects" as vbo
    rectangle Uniforms
}

rectangle Varyings
rectangle "Fragment Shader" as fs
rectangle "Frame Buffer" as fb

vbo <.. Attributes :Points to
vs <-- "Input" Uniforms
Uniforms "Input" --> fs


vs  "Output" -->  Varyings 
Varyings "Input" --> fs 

fs --> fb

@enduml
